Update metadata
abigpotostew/microcosmbot pull request #1
Opened 2023-06-20 05:42 UTC by jhernandezb

Use full URL instead of relative path which might fix sites not following relative paths

2023-06-20 06:07 UTC, abigpotostew commented on apps/web/constants/websiteMetadata.ts
> +  socialBanner: 'https://www.microcosmbot.xyz/images/hero.png',
It should use the env variable 

```
socialBanner: `${process.env.BASEURL}/images/hero.png'`
```

2023-06-20 06:07 UTC, abigpotostew requested changes
Use BASEURL env variable

2023-06-20 15:12 UTC, jhernandezb commented
updated

2023-06-21 04:20 UTC, abigpotostew approved these changes

2023-06-21 04:20 UTC, abigpotostew commented
Thank you!

2023-06-21 04:20 UTC, merged